version: '3.4'
services:
  postgres:
    container_name: ${CONTAINER_NAME:-postgres}
    hostname: ${CONTAINER_NAME:-postgres}
    image: postgres:${PG_VERSION:-16-alpine}
    volumes:
      - ./${DATA_FOLDER:-db_data}:/var/lib/postgresql/data
      - ./pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
      - ./pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
      # - ./dump:/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-postgres123}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-dblab}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - services
    ports:
      - ${PORT:-5434}:5432
    restart: always

  postgres2:
    container_name: postgres2
    hostname: postgres2
    image: postgres:${PG_VERSION:-16-alpine}
    volumes:
      - ./db_data2:/var/lib/postgresql/data
      - ./pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
      # - ./pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
      # - ./dump:/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-postgres123}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-dblab}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - services
    ports:
      - 5436:5432
    restart: always

# volumes:
#   metadata_data: {}

  pgadmin:
    # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
    container_name: pgadmin4
    hostname: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin123
    volumes:
      #- ./pgadmin_data:/data
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - services 
  
networks: 
  services:
    name: ${APP_NAME:-anisa}_network
volumes:
  pgadmin-data: {}