FROM bitnami/postgresql:16

USER root

# Install build dependencies
RUN apt-get update -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false || true && \
  apt-get install -y wget build-essential lsb-release libpq-dev \
                     liblz4-dev zlib1g-dev && \
  apt-get install -y cmake g++ sqlite3 libsqlite3-dev libtiff5-dev libcurl4-openssl-dev && \
  apt-get install -y libgeos-dev proj-bin libproj-dev git  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Add PostgreSQL repository
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# Install PostgreSQL development files
RUN apt-get update -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false || true && \
    apt-get install -y postgresql-server-dev-16 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download and compile pg_repack
RUN wget https://github.com/reorg/pg_repack/archive/ver_1.5.0.tar.gz && \
    tar xzf ver_1.5.0.tar.gz && \
    cd pg_repack-ver_1.5.0 && \
    make && \
    make install && \
    cd .. && \
    rm -rf pg_repack-ver_1.5.0 ver_1.5.0.tar.gz

COPY proj-9.4.1.tar.gz .
RUN tar xzf proj-9.4.1.tar.gz && \
    cd proj-9.4.1 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . && \
    cmake --build . --target install && \
    cd .. && \
    cd .. && \
    rm -rf proj-9.4.1 proj-9.4.1.tar.gz

COPY postgis-3.4.3dev.tar.gz .
RUN tar xzf postgis-3.4.3dev.tar.gz && \
    cd postgis-3.4.3dev && \
    ./configure  --without-protobuf && \
    make && \
    make install && \
    cd .. && \
    rm -rf postgis-3.4.3dev postgis-3.4.3dev.tar.gz


# Set the library path
ENV LD_LIBRARY_PATH /opt/bitnami/postgresql/lib:$LD_LIBRARY_PATH

USER 1001

