version: '3'

services:
  haproxy:
    image: haproxy
    ports:
      - "5432:5432"
      - "5433:5433"
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  patroni:
    image: patroni-image
    build:
      context: .
      dockerfile: DockerfilePatroni
    networks:
      - postgres-backend
    ports:
      - "8008:8008"
      - "6432:5432"
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./patroni.yml:/etc/patroni.yml
    environment:
      TZ: Asia/Tehran
      PATRONI_NAME: member_1
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data/node1
      PATRONI_CONSUL_HOST: http://consul:8500
      PATRONI_CONSUL_URL: http://consul:8500/v1/
    restart: unless-stopped

  pgbouncer:
    image: edoburu/pgbouncer
    networks:
      - postgres-backend
    ports:
      - "5432:5432"
    depends_on:
      - patroni
    environment:
      TZ: Asia/Tehran
      ADMIN_USERS: admin
      DB_HOST: patroni
      DB_USER: admin
      DB_PASSWORD: admin
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 300
    restart: unless-stopped

  consul:
    image: consul:1.15
    hostname: "${HOSTNAME}"
    environment:
      TZ: Asia/Tehran
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul-data:/data
    restart: unless-stopped
    command: agent -server -advertise 10.128.0.18 -bootstrap-expect 3 -client 0.0.0.0 -retry-join 10.128.0.18 -retry-join 10.128.0.98 -retry-join 10.128.0.99

networks:
  postgres-backend:

volumes:
  postgres-data:
  consul-data:
